/* eslint-disable unused-imports/no-unused-vars-ts */

import { useEthersAdaptorFromProviderOrSigners } from 'eth-hooks'
import { useEthersAppContext } from 'eth-hooks/context'
import { asEthersAdaptor } from 'eth-hooks/functions'
import Head from 'next/head'
import React from 'react'

import { Header } from '../Header'

import { Subscription } from './Subscription'

import { useAppContracts, useConnectAppContracts, useLoadAppContracts } from '~common/components/context'
import { useCreateAntNotificationHolder } from '~common/components/hooks/useAntNotification'
import { useScaffoldAppProviders } from '~common/components/hooks/useScaffoldAppProviders'
import {
  ALCHEMY_KEY,
  CONNECT_TO_BURNER_AUTOMATICALLY,
  LOCAL_PROVIDER,
  MAINNET_PROVIDER,
  TARGET_NETWORK_INFO,
} from '~~/config/app.config'
import { useLoadUserOnWalletConnect } from '~~/hooks/useLoadUserOnWalletConnect'
import { useAppSelector } from '~~/redux/hooks'

interface UserDashboardPageProps {}

export const UserDashboardPage: React.FC<UserDashboardPageProps> = ({}) => {
  const notificationHolder = useCreateAntNotificationHolder()
  useLoadUserOnWalletConnect()
  const { initiated, loading } = useAppSelector((state) => state.subs)

  // -----------------------------
  // Providers, signers & wallets
  // -----------------------------
  // 🛰 providers
  // see useLoadProviders.ts for everything to do with loading the right providers
  const scaffoldAppProviders = useScaffoldAppProviders({
    targetNetwork: TARGET_NETWORK_INFO,
    connectToBurnerAutomatically: CONNECT_TO_BURNER_AUTOMATICALLY,
    localProvider: LOCAL_PROVIDER,
    mainnetProvider: MAINNET_PROVIDER,
    alchemyKey: ALCHEMY_KEY,
  })

  // 🦊 Get your web3 ethers context from current providers
  const context = useEthersAppContext()

  // -----------------------------
  // Load Contracts
  // -----------------------------
  // 🛻 load contracts
  useLoadAppContracts()
  // 🏭 connect to contracts for mainnet network & signer
  const [mainnetAdaptor] = useEthersAdaptorFromProviderOrSigners(MAINNET_PROVIDER)
  useConnectAppContracts(mainnetAdaptor)
  // 🏭 connec to  contracts for current network & signer
  useConnectAppContracts(asEthersAdaptor(context))

  // init contracts
  const Subscription_SuperApp = useAppContracts('SSA', context.chainId)

  return (
    <div>
      <Head>
        <title>🥪 Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header scaffoldAppProviders={scaffoldAppProviders} />

      <div className="h-screen flex justify-center">
        <div className="w-full max-w-4xl pt-24">
          {loading ? (
            <h1>Loading...</h1>
          ) : initiated ? (
            <>
              <h1>Your subscriptions</h1>
              <div className="h-px bg-gray-200" />
              <div className="pt-16 grid grid-cols-2 gap-8">
                <Subscription />
                <Subscription />
                <Subscription />
                <Subscription />
              </div>
            </>
          ) : (
            <h1>Please connect your wallet</h1>
          )}
          {}
        </div>
      </div>

      <div style={{ position: 'absolute' }}>{notificationHolder}</div>
    </div>
  )
}

export default UserDashboardPage
