import Head from 'next/head'
import React from 'react'

import { TSubstation } from '~~/pages/user/substations'
import { Substation } from './SubstationInsight'

interface SubstationsInsightPageProps {
  substations: TSubstation[]
}

export const SubstationInsightPage: React.FC<SubstationsInsightPageProps> = ({ substations }) => {
  return (
    <>
      <Head>
        <title>🥪 Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-20 flex flex-col items-center space-y-4">
        <h1>Your Substations</h1>
        {substations.map((s, i) => (
          <Substation
            key={s.name + i}
            name={s.name}
            symbol={s.symbol}
            address={s.address}
            balance={s.balance}
            balanceTimestamp={s.balanceTimestamp}
            flowRate={s.flowRate}
            tiers={s.tiers}
          />
        ))}
      </div>

      <div className="sticky bottom-0 text-center text-white font-bold w-full h-8 pt-2 bg-green-400">
        This page is usually only available to creators of the SubStation (where user can subscribe to). For demo
        purposes it can be viewed by all.
      </div>
    </>
  )
}

export default SubstationInsightPage
